# Generated by Django 3.2.6 on 2021-10-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='motes',
            new_name='votes',
        ),
    ]
