# Generated by Django 3.2.6 on 2021-11-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.DateField()),
                ('company', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
