# Generated by Django 3.2.6 on 2021-11-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.DateField(verbose_name='Birthday date'),
        ),
        migrations.AlterField(
            model_name='human',
            name='company',
            field=models.CharField(max_length=50, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=30, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='human',
            name='salary',
            field=models.IntegerField(verbose_name='Your salary'),
        ),
        migrations.AlterField(
            model_name='human',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='User surname'),
        ),
    ]
