# Generated by Django 3.2.6 on 2021-11-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth', models.DateField()),
                ('company', models.CharField(choices=[('google', 'Google'), ('yandex', 'Yandex'), ('itvdn', 'Itvdn'), ('epam', 'Epam')], max_length=150)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
